<?php

namespace Database\Seeders;

use App\Models\Experience;
use Illuminate\Database\Seeder;

class ExperienceSeeder extends Seeder
{
    public function run(): void
    {
        $experiences = [
            [
                'name' => '田植え体験',
                'description' => '南信州の棚田で昔ながらの田植えを体験します。裸足で泥の中に入り、一本一本苗を丁寧に植える作業を通じて、食の大切さと農業のすばらしさを実感できます。地元農家の方が丁寧に指導しますので、初めての方も安心です。',
                'price' => 4500,
                'price_note' => '¥4,500 / 人',
                'pricing_type' => 'per_person',
                'duration' => '約 2〜3 時間',
                'recommended_people' => '2〜6 名',
                'season' => null,
                'season_tag' => '春',
                'period' => '5〜6 月',
                'period_start' => '04-25',
                'period_end' => '06-14',
                'requires_reservation' => true,
                'points' => [
                    '長靴・汚れてもよい服装でご参加ください（貸し出し要相談）',
                    '春の新野の清々しい空気の中で心身とにリフレッシュ',
                    '地元農家さんとの交流が旅の思い出になります',
                ],
                'notes' => '前日までのご予約が必要です。当日の天候により内容を変更する場合がありす。',
                'popularity' => 0,
                'is_active' => true,
                'sort_order' => 0,
            ],
            [
                'name' => '稲刈り体験',
                'description' => '黄金色に輝く稲穂を鎌で刈り取る秋の収穫体験です。自分の手で稲を刈り取り、束ねる作業は達成感もひとしお。収穫された米がどのように食卓に届くかを体感できる、特別なひとときです。',
                'price' => 4500,
                'price_note' => '¥4,500 / 人',
                'pricing_type' => 'per_person',
                'duration' => '約 2〜3 時間',
                'recommended_people' => '2〜6 名',
                'season' => null,
                'season_tag' => '秋',
                'period' => '9〜10 月',
                'period_start' => '09-07',
                'period_end' => '10-31',
                'requires_reservation' => true,
                'points' => [
                    '鎌の使い方から丁寧に指導します（安全を最優先）',
                    '収穫したお米の一部をお土産としてお持ち帰りいただけます（量は応相談）',
                    '秋の高原の澄んだ空気と黄金の棚田の景色は絶景です',
                ],
                'notes' => '前日までのご予約が必要です。当日の天候により内容を変更する場合がありす。',
                'popularity' => 0,
                'is_active' => true,
                'sort_order' => 0,
            ],
            [
                'name' => '薪割り体験',
                'description' => '斧を振るって薪を割る、爽快でシンプルな体験です。薪ストーブ用の薪を自分の手で割ることで、暖かな夜の火を囲む喜びが格段に増します。普段使わない筋肉を使い、心身ともにリフレッシュできます。',
                'price' => 2000,
                'price_note' => '¥2,000 / 1組',
                'pricing_type' => 'per_group',
                'duration' => '1 時間単位',
                'recommended_people' => '1〜6 名',
                'season' => null,
                'season_tag' => '通年',
                'period' => '通年',
                'period_start' => null,
                'period_end' => null,
                'requires_reservation' => false,
                'points' => [
                    '斧・楔（くさび）・安全手袋はすべて貸し出しします',
                    '10 歳以上から体験可（お子さまは保護者同伴）',
                    '割った薪はそのまま薪ストーブでお使いいただけます',
                ],
                'notes' => '事前予約なしでも当日お申込みいただけます（準備の都合上、前日までのご連絡を推奨）。当日の天候により内容を変更する場合がありす。',
                'popularity' => 0,
                'is_active' => true,
                'sort_order' => 0,
            ],
            [
                'name' => '夏野菜収穫体験',
                'description' => '標高が高く涼しい新野の高原で育った新鮮な夏野菜を自分で収穫します。トマト・きゅうり・ナス・とうもろこしなど、旬の野菜を摘みたてで味わえます。収穫した野菜はその日の夕食やBBQにそのまま使えます。',
                'price' => 1500,
                'price_note' => '¥1,500 / 人',
                'pricing_type' => 'per_person',
                'duration' => '約 30〜60 分',
                'recommended_people' => '1〜6 名',
                'season' => null,
                'season_tag' => '夏',
                'period' => '7〜8 月',
                'period_start' => '07-21',
                'period_end' => '09-07',
                'requires_reservation' => true,
                'points' => [
                    '収穫したものはすべてお持ち帰りOK',
                    'お子さまの食育体験としても大変人気があります',
                    'BBQグリルレンタルとの組み合わせが特におすすめです',
                ],
                'notes' => '野菜の生育状況により収穫できる品目が変わります。当日の天候により内容を変更する場合がありす。',
                'popularity' => 0,
                'is_active' => true,
                'sort_order' => 0,
            ],
            [
                'name' => '散歩',
                'description' => '巣山湖のほとりや新野の里山をのんびり歩く、心地よい散歩コースが楽しめます。春は桜、夏は川遊び、秋は実る果物、冬は雪景色と、四季それぞれに異なる表情を見せる南信州の自然をお楽しみください。',
                'price' => 0,
                'price_note' => '無料',
                'pricing_type' => 'per_group',
                'duration' => '自由',
                'recommended_people' => '1〜6 名',
                'season' => null,
                'season_tag' => '通年',
                'period' => '通年',
                'period_start' => null,
                'period_end' => null,
                'requires_reservation' => false,
                'points' => [
                    '春：巣山湖周辺の桜並木と芽吹きの緑が見事です',
                    '夏・秋：小川での川遊びや、道端で実る果物との出会いも',
                    '冬：白銀に包まれた静寂の雪景色は格別のひとときです',
                ],
                'notes' => '足元に適した靴でお出かけください。冬期は積雪・凍結にご注意ください。',
                'popularity' => 0,
                'is_active' => true,
                'sort_order' => 0,
            ],
            [
                'name' => '草刈り体験',
                'description' => 'ラジコン草刈り機「カルゾー」の操作を体験できます。コントローラーひとつで力強く草を刈り取るロボットの動きは、大人もお子さまも夢中になる楽しさ。里山の景観維持にも貢献する、新しいかたちの田舎体験です。',
                'price' => 3000,
                'price_note' => '¥3,000 / 1組',
                'pricing_type' => 'per_group',
                'duration' => '約 30〜60 分',
                'recommended_people' => '1〜3 名',
                'season' => null,
                'season_tag' => '夏',
                'period' => '3月～10月',
                'period_start' => '03-20',
                'period_end' => '10-31',
                'requires_reservation' => true,
                'points' => [
                    'ラジコン操作なので体力に自信がない方でも気軽に楽しめます',
                    'お子さまも保護者同伴で操作体験OK（安全指導付き）',
                    '急斜面もパワフルに刈り取るカルゾーの走破力は圧巻です',
                ],
                'notes' => '事前予約なしでも当日お申込みいただけます。天候や機体整備の状況により体験できない場合があります。',
                'popularity' => 0,
                'is_active' => true,
                'sort_order' => 0,
            ],
            [
                'name' => '星空観察（ガイドなし）',
                'description' => '双眼鏡の無料貸出あり。新野の満天の星をお楽しみください。',
                'price' => 0,
                'price_note' => '無料',
                'pricing_type' => 'per_group',
                'duration' => null,
                'recommended_people' => null,
                'season' => '通年（晴天時）',
                'season_tag' => '通年',
                'period' => null,
                'period_start' => null,
                'period_end' => null,
                'requires_reservation' => false,
                'points' => [],
                'notes' => null,
                'popularity' => 0,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => '星空ガイド付き観察',
                'description' => '地元ガイドが星座・天体を解説。望遠鏡もご用意。',
                'price' => 2000,
                'price_note' => '¥2,000 / 1組',
                'pricing_type' => 'per_group',
                'duration' => null,
                'recommended_people' => null,
                'season' => '通年（晴天時）',
                'season_tag' => '通年',
                'period' => null,
                'period_start' => null,
                'period_end' => null,
                'requires_reservation' => true,
                'points' => [],
                'notes' => null,
                'popularity' => 0,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'BBQプラン',
                'description' => 'BBQグリル・炭・網のセットをご用意します。',
                'price' => 2000,
                'price_note' => '¥2,000 / 人',
                'pricing_type' => 'per_person',
                'duration' => null,
                'recommended_people' => null,
                'season' => null,
                'season_tag' => '通年',
                'period' => null,
                'period_start' => null,
                'period_end' => null,
                'requires_reservation' => true,
                'points' => [],
                'notes' => null,
                'popularity' => 0,
                'is_active' => true,
                'sort_order' => 3,
            ],
        ];

        foreach ($experiences as $experience) {
            Experience::firstOrCreate(['name' => $experience['name']], $experience);
        }
    }
}
